#!/bin/sh

append_to_file() {
  local text="$1"
  local file="$2"

  if ! grep -Fsq "$text" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

main(){
  source_cmd="source $HOME/.adshell/custom"

  append_to_file "$source_cmd" $HOME/.bashrc
  append_to_file "$source_cmd" $HOME/.zshrc
}

# Run main().
# This is wrapped to avoid the concerns about disconnects before the whole script is curled.
main
